apiVersion: v1
kind: Secret
metadata:
  name: nebula-secrets
  namespace: nebula
type: Opaque
data:
  database-url: <SECRET_8e6baff1>sI3ZTEyYiRiOiJiNGIzOTFhMi1iOWQ2LTQ3YjYtODJmZi02YjZiOTg0NWNhYWEiLCJpYXQiOjE3MjI1Mjg1NzZ9.eyJzdWIiOiI5IiwidXNlciI6eyJlbWFpbCI6InRlc3RlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoidGVzdGVyIn19.2F9Z_GsKVJ2f8u_2K7mdB6Y
  redis-url: <SECRET_89e7d8b7>0hMiRiOiJiNGIzOTFhMi1iOWQ2LTQ3YjYtODJmZi02YjZiOTg0NWNhYWEiLCJpYXQiOjE3MjI1Mjg1NzZ9.eyJzdWIiOiI5IiwidXNlciI6eyJlbWFpbCI6InRlc3RlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoidGVzdGVyIn19.2F9Z_GsKVJ2f8u_2K7mdB6Y
  jwt-secret: <SECRET_1e3d048b>jJiOiJiNGIzOTFhMi1iOWQ2LTQ3YjYtODJmZi02YjZiOTg0NWNhYWEiLCJpYXQiOjE3MjI1Mjg1NzZ9.eyJzdWIiOiI5IiwidXNlciI6eyJlbWFpbCI6InRlc3RlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoidGVzdGVyIn19.2F9Z_GsKVJ2f8u_2K7mdB6Y
  encryption-key: <SECRET_982c072f>yRiOiJiNGIzOTFhMi1iOWQ2LTQ3YjYtODJmZi02YjZiOTg0NWNhYWEiLCJpYXQiOjE3MjI1Mjg1NzZ9.eyJzdWIiOiI5IiwidXNlciI6eyJlbWFpbCI6InRlc3RlckBleGFtcGxlLmNvbSIsInVzZXJuYW1lIjoidGVzdGVyIn19.2F9Z_GsKVJ2f8u_2K7mdB6Y